# ???? ??
# https://curiousjinan.tistory.com/entry/spring-boot-tomcat-environment
jwt:
  # ????
  header: Authorization
  # jwt ??? ?? salt
  secret: sdgfhjaklsdhjkhasgfhjasgfhjsdfgkjhsadgfhkjsdgfkhjsdgkj
  # ????
  expire_time: 600 # 10 min

spring:
  security:
    user:
      name: user
      password: password
  datasource:
    url: jdbc:sqlite:db.sqlite
    driver-class-name: org.sqlite.JDBC
    username: sa
    password: password

  jpa:
    hibernate:
      format_sql: true
      ddl-auto: create
    show-sql: true
    # table create í›„ data.sql initialize
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      username: ${REDIS_USERNAME}
      password: ${REDIS_PASSWORD}


springdoc:
  swagger-ui:
    display-request-duration: true
  api-docs:
    path: /v1/api-docs

  paths-to-match:
    - /api/v1/**